spring.application.name=Bank
spring.datasource.url=jdbc:mysql://localhost:3306/bank_details
spring.datasource.username=root
spring.datasource.password=Madhan@009
spring.jpa.hibernate.ddl-auto=update
server.port=8081